// Auto generated file from SBConstants - any changes may be lost

public enum SegueIdentifier : String {
    case ArtsyUserHasNotRegisteredCard = "Artsy User Has Not Registered Card"
    case ArtsyUserviaPINHasNotRegisteredCard = "Artsy User via PIN Has Not Registered Card"
    case ConfirmBid = "Confirm Bid"
    case ConfirmyourBidArtsyLogin = "Confirm your Bid - Artsy Login"
    case ConfirmyourBidBidderFound = "Confirm your Bid - Bidder Found"
    case ConfirmyourBidBidderNotFound = "Confirm your Bid - Bidder Not Found"
    case EmailLoginConfirmedHighestBidder = "Email Login Confirmed Highest Bidder"
    case EmailNotFoundonArtsy = "Email Not Found on Artsy"
    case ExistingArtsyUserFound = "Existing Artsy User Found"
    case LoadAdminWebViewController = "Load Admin Web View Controller"
    case LoadWebView = "Load Web View"
    case PINConfirmedhasCard = "PIN Confirmed has Card"
    case PushtoBidConfirmed = "Push to Bid Confirmed"
    case RegisterCreditCardToPostal = "RegisterCreditCardToPostal"
    case RegisterPostalToConfirm = "RegisterPostalToConfirm"
    case RegistrationFinishedPlaceBid = "Registration Finished Place Bid"
    case RegistrationFinishedShowBidDetails = "Registration Finished Show Bid Details"
    case ShowAdminOptions = "Show Admin Options"
}

public enum ViewControllerStoryboardIdentifier : String {
    case ConfirmYourBid = "Confirm Your Bid"
    case ConfirmYourBidArtsyLogin = "Confirm Your Bid Artsy Login"
    case ConfirmYourBidEnterEmail = "Confirm Your Bid Enter Email"
    case ConfirmYourBidEnterPassword = "Confirm Your Bid Enter Password"
    case ConfirmYourBidPIN = "Confirm Your Bid PIN"
    case FulfillmentContainer = "Fulfillment Container"
    case PlaceYourBid = "Place Your Bid"
    case RegisterAnAccount = "Register An Account"
    case RegisterConfirm = "Register Confirm "
    case RegisterCreditCard = "Register Credit Card"
    case RegisterEmail = "Register Email"
    case RegisterMobile = "Register Mobile"
    case RegisterPassword = "Register Password"
    case RegisterPostalorZip = "Register Postal or Zip"
    case WebViewController = "Web View Controller"
}
