// Auto generated file from SBConstants - any changes may be lost

enum SegueIdentifier : String {
    case ArtsyUserHasNotRegisteredCard = "Artsy User Has Not Registered Card"
    case ArtsyUserviaPINHasNotRegisteredCard = "Artsy User via PIN Has Not Registered Card"
    case ConfirmBid = "Confirm Bid"
    case ConfirmyourBidArtsyLogin = "Confirm your Bid - Artsy Login"
    case ConfirmyourBidBidderFound = "Confirm your Bid - Bidder Found"
    case ConfirmyourBidBidderNotFound = "Confirm your Bid - Bidder Not Found"
    case EmailLoginConfirmedHighestBidder = "Email Login Confirmed Highest Bidder"
    case EmailNotFoundonArtsy = "Email Not Found on Artsy"
    case ExistingArtsyUserFound = "Existing Artsy User Found"
    case LoadAdminWebViewController = "Load Admin Web View Controller"
    case PINConfirmedhasCard = "PIN Confirmed has Card"
    case PlaceAnotherBid = "Place Another Bid"
    case PlaceaHigherBidAfterNotBeingHighestBidder = "Place a Higher Bid After Not Being Highest Bidder"
    case PushtoRegisterConfirmed = "Push to Register Confirmed"
    case RegisterCreditCardToPostal = "RegisterCreditCardToPostal"
    case RegisterPostalToConfirm = "RegisterPostalToConfirm"
    case ShowAdminOptions = "Show Admin Options"
    case ShowLoadingView = "Show Loading View"
    case ShowSaleArtworkDetails = "Show Sale Artwork Details"
    case UNUSEDManualcreditcard = "UNUSED Manual credit card"
    case UNUSEDPushtoSwipeCreditCard = "UNUSED Push to Swipe Credit Card"
    case UNUSEDPushtoemail = "UNUSED Push to email"
    case UNUSEDPushtoentermobilenumber = "UNUSED Push to enter mobile number"
    case UNUSEDPushtopassword = "UNUSED Push to password"
    case ZoomIntoArtwork = "Zoom Into Artwork"
}

enum StoryboardNames : String {
    case Auction = "Auction"
    case Fulfillment = "Fulfillment"
}

enum ViewControllerStoryboardIdentifier : String {
    case AppViewController = "AppViewController"
    case AuctionListings = "AuctionListings"
    case CardTester = "Card Tester"
    case ConfirmYourBid = "Confirm Your Bid"
    case ConfirmYourBidArtsyLogin = "Confirm Your Bid Artsy Login"
    case ConfirmYourBidEnterEmail = "Confirm Your Bid Enter Email"
    case ConfirmYourBidEnterPassword = "Confirm Your Bid Enter Password"
    case ConfirmYourBidPIN = "Confirm Your Bid PIN"
    case FulfillmentContainer = "Fulfillment Container"
    case LoadingBidsorRegistering = "Loading Bids or Registering"
    case ManualCardDetailsInput = "Manual Card Details Input"
    case NoInternetConnection = "No Internet Connection"
    case PlaceYourBid = "Place Your Bid"
    case RegisterAnAccount = "Register An Account"
    case RegisterConfirm = "Register Confirm "
    case RegisterCreditCard = "Register Credit Card"
    case RegisterEmail = "Register Email"
    case RegisterMobile = "Register Mobile"
    case RegisterPassword = "Register Password"
    case RegisterPostalorZip = "Register Postal or Zip"
    case SaleArtworkDetail = "SaleArtworkDetail"
    case YourBidderDetails = "Your Bidder Details"
}
